# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Update images

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun install

            - name: Update images
              shell: bash
              run: |
                  git config --global user.email "vigovlugt@gmail.com"
                  git config --global user.name "League of Items Github Action"
                  ./update-images.sh
